# Generated by Django 4.1.4 on 2022-12-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_one', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
