# Generated by Django 4.1.4 on 2022-12-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('year', models.IntegerField(max_length=4)),
                ('genre', models.CharField(choices=[('фантастика', 'fantasy'), ('боевик', 'thriller'), ('детектив', 'detective'), ('комедия', 'comedy'), ('мелодрама', 'melodrama'), ('научный', 'science'), ('приключения', 'adventures'), ('ужасы', 'horror'), ('спорт', 'sport'), ('мультфильм', 'cartoon'), ('документальный', 'documentary')], max_length=20)),
                ('producer', models.CharField(max_length=70)),
                ('actors', models.TextField()),
                ('duration', models.TimeField()),
                ('image', models.ImageField(upload_to='films')),
                ('video', models.FileField(upload_to='films')),
            ],
        ),
    ]
