# Generated by Django 4.1.4 on 2022-12-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_film_duration_alter_film_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('фантастика', 'fantasy'), ('боевик', 'thriller'), ('детектив', 'detective'), ('комедия', 'comedy'), ('мелодрама', 'melodrama'), ('научный', 'science'), ('приключения', 'adventures'), ('ужасы', 'horror'), ('спорт', 'sport'), ('мультфильм', 'cartoon'), ('документальный', 'documentary')], max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(max_length=100),
        ),
    ]
